package raft

const MIN_ELECTION_TIMEOUT = 200
const MAX_ELECTION_TIMEOUT = 350

const MIN_RPC_TIMEOUT = 100
const MAX_RPC_TIMEOUT = 150

const MIN_HEARTBEAT_SEND_WAIT = 50
const MAX_HEARTBEAT_SEND_WAIT = 100
