package utils

const MIN_ELECTION_TIMEOUT_MS = 200
const MAX_ELECTION_TIMEOUT_MS = 350
const HEARTBEAT_SEND_WAIT_MS = 100

const BASE_CLIENT_RETRY_WAIT_MS = 100
const BACKOFF_EXPONENT = 2
const MAX_RPC_RETRIES = 3
const RPC_TIMEOUT_MS = 80
