package utils

const MIN_ELECTION_TIMEOUT_MS = 200
const MAX_ELECTION_TIMEOUT_MS = 350

const MIN_HEARTBEAT_SEND_WAIT_MS = 130
const MAX_HEARTBEAT_SEND_WAIT_MS = 150

const BASE_CLIENT_RETRY_WAIT_MS = 100
const BACKOFF_EXPONENT = 2
const RANDOMIZE_AFTER_RETRY_COUNT = 3
